version: "3.8"
services:
  sofia-chat-frontend-v2:
    container_name: sofia-chat-frontend-v2
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - sofia_chat_network

networks:
  sofia_chat_network:
