version: "3.8"
services:
  sofia-chat-frontend-v2:
    container_name: sofia-chat-frontend-v2-${PORT:-3000}
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    networks:
      - sofia_chat_network

networks:
  sofia_chat_network:
