version: "3.8"
services:
  converxa-chat-frontend:
    container_name: converxa-chat-frontend-${PORT:-3000}
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    networks:
      - converxa_chat_network

networks:
  converxa_chat_network:
