name: Auto deploy converxa-chat-frontend internal in VPS

on:
  push:
    branches:
      - release
    paths:
      - ".github/workflows/**"
      - "index.html"
      - "package.json"
      - "public/**"
      - "scripts/**"
      - "src/**"
      - "vite.config.js"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 137.184.44.230
          username: root
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/repos/converxa-chat-frontend
            git fetch origin
            git checkout release
            git pull origin release
            npm ci
            cat <<EOF > .env
            VITE_API_URL=https://internal-back.converxa.com
            VITE_ENVIRONMENT=staging
            VITE_WSS_URL=wss://internal-back.converxa.com
            VITE_FILES_URL=https://internal-back.converxa.com/files
            VITE_PUBLIC_BACKEND_URL=https://internal-back.converxa.com
            VITE_PUBLIC_TOKEN_NAME=token
            VITE_PUBLIC_TOKEN_REFRESH_NAME=refreshToken
            VITE_PUBLIC_URL_FILES=https://internal-back.converxa.com/files
            VITE_BACKEND_URL_FILES=https://internal-back.converxa.com/files
            VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}
            VITE_FB_APP_ID=${{ secrets.VITE_FB_APP_ID }}
            VITE_FB_CONFIG_ID=${{ secrets.VITE_FB_CONFIG_ID }}
            EOF
            npm run build -- --mode staging
            rm -rf /var/www/frontend/internal/*
            cp -r dist/* /var/www/frontend/internal/
