name: Auto deploy converxa-chat-frontend development in VPS (DISABLED)

on:
  push:
    branches:
      - dev-disabled # Branch disabled - does not exist
    paths:
      - ".github/workflows/**"
      - "index.html"
      - "package.json"
      - "public/**"
      - "scripts/**"
      - "src/**"
      - "vite.config.js"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev-disabled # Disabled branch

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }} # Asegúrate de que este secret esté configurado
          username: ${{ secrets.DEV_SSH_USERNAME }} # Asegúrate de que este secret esté configurado
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }} # Asegúrate de que este secret esté configurado
          port: 22
          script: |
            cd /root/repos/converxa-chat-frontend
            git fetch origin
            git checkout dev-disabled  # Disabled branch
            git pull origin dev-disabled  # Disabled branch
            cat <<EOF > .env
            VITE_PUBLIC_BACKEND_URL=${{ secrets.VITE_PUBLIC_BACKEND_URL_DEV }}  # Cambia a la URL de desarrollo
            VITE_PUBLIC_TOKEN_NAME=${{ secrets.VITE_PUBLIC_TOKEN_NAME_DEV }}
            VITE_PUBLIC_TOKEN_REFRESH_NAME=${{ secrets.VITE_PUBLIC_TOKEN_REFRESH_NAME_DEV }}
            VITE_PUBLIC_URL_FILES=${{ secrets.VITE_PUBLIC_URL_FILES_DEV }}  # Cambia a la URL de desarrollo
            VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID_DEV }}
            VITE_FB_APP_ID=${{ secrets.VITE_FB_APP_ID_DEV }}
            VITE_FB_CONFIG_ID=${{ secrets.VITE_FB_CONFIG_ID_DEV }}
            VITE_FB_MESSENGER_CONFIG_ID=1058554123005287
            NODE_OPTIONS="--max-old-space-size=1536"
            EOF
            export NODE_OPTIONS="--max-old-space-size=1536"
            docker-compose build  # Usa un archivo de compose específico para desarrollo
            docker-compose down -v
            docker-compose up -d
